### ISSUE TITLE
Wierd but only way

### ISSUE THREAD

**Issue by ThundR67** [Superposition-Labs/ave#1]
I was trying to use your disentangle model on custom data but couldn't figure out how too. Your fork didn't have issues so creating issue here. Apologies for that. Do you have guide on how to do it?

**Comment by scvsh** [comment]
We explored the BERT Disentangle but ultimately resorted to LM processing using smaller models, inference cost was comparable and the results much better than bert

**Comment by ThundR67** [comment]
How did you use LM models for it. An approach I was trying was to figure out all questions and treat them as start of conversation. However its not very accurate.
